---
title: "BARBIE_Workflow"
author: "PJ"
date: "5/14/2018"
output: html_document
---

Install packages: 
```{r install-pkgs,message=FALSE,warning=FALSE,results='hide'}
pkgs <- c("ggplot2","reshape2","VennDiagram","stringr","gdata","Rmisc","corrplot","dplyr","coin","tidyr","xtable","grid","phyloseq","DESeq2","preprocessCore","HDInterval","gridExtra","gtable","BiocParallel","doParallel","parallel","pracma")
```

load packages:
```{r load-pkgs,message=FALSE,warning=FALSE,results='hide'}
lpckges<-pkgs%in%(.packages())
if(any(!lpckges)){
    sapply(pkgs[!lpckges],require,character.only=TRUE)
}
```

Read phyloseq 
```{r read-phylo,message=FALSE,warning=FALSE}
ps <- readRDS("/Users/jpratheepa31/Dropbox/GitHub/sepsis_project/SIRS/Data/ps_sirs_updated_apr_20_2018.rds")
```

Remove library control
```{r remove-unwanted-controls,message=FALSE,warning=FALSE}
ps <- subset_samples(ps,Sample_Type=!"Library_Control")
```

Adding blocks
```{r adding-blocks,message=FALSE,warning=FALSE}
set1 <- c("1","2","3","4","11","12")
set2 <- c("5","6","7","8","9","10")
setP <- "P"
ext.num <- sample_data(ps)$Extraction_Number

blocks <-ifelse(ext.num %in% set1, "Set1", ifelse(ext.num %in% set2, "Set2", "SetP"))

sample_data(ps)$block <- blocks
```

preprocessing samples:
```{r }
if(dim(otu_table(ps))[1]!=ntaxa(ps)){otu_table(ps) <- t(otu_table(ps))}

#   total reads per sample
totalReads <- colSums(otu_table(ps))

#   distribution of total reads per sample
hist(log(totalReads),yaxs="i",xaxs="i",main="Distribution of total reads per sample",breaks=50)

#   select SIRS samples, healthy samples, and negative controls 
ps <- subset_samples(ps,SampleType %in% c("SIRS","Control","Healthy"))
```


Preprocessing taxa 
```{r filter-taxa,message=FALSE,warning=FALSE}
#   drop taxa with no reads
ps <- prune_taxa(taxa_sums(ps)>0,ps)
ps

#   taxa not in any of plasma samples - 
prevTaxaP <- apply(otu_table(subset_samples(ps,Sample_Type%in%"Plasma")),1,function(x){sum(x>0)})
#   taxa not in any of plasma samples are identified as contaminants
Contaminants1 <- names(prevTaxaP)[prevTaxaP==0]
ps <- prune_taxa(prevTaxaP>0,ps)
ps
```



Summary statistics
```{r summary-stat,message=FALSE,warning=FALSE}
table(sample_data(ps)$Sample_Type,sample_data(ps)$block)
```




```{r block-phylos,message=FALSE,warning=FALSE}
psBlockResult <- psBlockResults(ps,sampleTypeVar="Sample_Type",blockVar="block")
psByBlock <- psBlockResult[[1]]
psNCbyBlock <- psBlockResult[[2]]
psallzeroInNC <- psBlockResult[[3]]
psPlByBlock <- psBlockResult[[4]]
```


```{r estimate-neg-bio-para-ncontrols,message=FALSE,warning=FALSE}
alphaBetaNegControl <- alphaBetaNegControl(psNCbyBlock=psNCbyBlock)
```


```{r estimate-cont-for-plasma-sam,message=FALSE,warning=FALSE}
gammPrior <- alphaBetaContInPlasma(psPlByBlock = psPlByBlock,psallzeroInNC=psallzeroInNC,blk = 3,alphaBetaNegControl=alphaBetaNegControl)
```

```{r estim-poster-real-reads,message=FALSE,warning=FALSE}
taxa.post.all.sam  <- samplingPosterior(psPlByBlock=psPlByBlock,blk=3,gammPrior=gammPrior,iter=10)
```

