---
title: "BARBIE_Workflow"
author: "PJ"
date: "5/14/2018"
output: html_document
---

Install packages: 
```{r install-pkgs,message=FALSE,warning=FALSE,results='hide'}
pkgs <- c("DESeq2","phyloseq","dplyr","tidyr","R.utils","BiocParallel","doParallel","parallel","HDInterval","grid","xtable","gtable","gridExtra")
```

load packages:
```{r load-pkgs,message=FALSE,warning=FALSE,results='hide'}
lpckges<-pkgs%in%(.packages())
if(any(!lpckges)){
    sapply(pkgs[!lpckges],require,character.only=TRUE)
}
#devtools::load_all(".")
sourceDirectory("./R")
```

Read phyloseq 
```{r read-phylo,message=FALSE,warning=FALSE}
ps <- readRDS("/Users/jpratheepa31/Dropbox/GitHub/SIRS/Data/ps_sirs_updated_may_1_2018.rds")
```

Remove library control
```{r remove-unwanted-controls,message=FALSE,warning=FALSE}
ps <- subset_samples(ps,Sample_Type=!"Library_Control")
```

Adding blocks
```{r adding-blocks,message=FALSE,warning=FALSE}
set1 <- c("1","2","3","4","11","12")
set2 <- c("5","6","7","8","9","10")
setP <- "P"
ext.num <- sample_data(ps)$Extraction_Number

blocks <-ifelse(ext.num %in% set1, "Set1", ifelse(ext.num %in% set2, "Set2", "SetP"))

sample_data(ps)$block <- blocks
```

Preprocessing taxa 
```{r filter-taxa,message=FALSE,warning=FALSE}
#   drop taxa with no reads
ps <- prune_taxa(taxa_sums(ps)>0,ps)
ps

#   taxa not in any of plasma samples - 
prevTaxaP <- apply(otu_table(subset_samples(ps,Sample_Type%in%"Plasma")),1,function(x){sum(x>0)})
#   taxa not in any of plasma samples are identified as contaminants
Contaminants1 <- names(prevTaxaP)[prevTaxaP==0]
ps <- prune_taxa(prevTaxaP>0,ps)
ps
```

preprocessing samples:
```{r filter-samples}
if(dim(otu_table(ps))[1]!=ntaxa(ps)){otu_table(ps) <- t(otu_table(ps))}

#   total reads per sample
totalReads <- colSums(otu_table(ps))

#   distribution of total reads per sample
hist(log(totalReads),yaxs="i",xaxs="i",main="Distribution of total reads per sample",breaks=50)

#   select SIRS samples, healthy samples, and negative controls 
ps <- subset_samples(ps,SampleType %in% c("SIRS","Control","Healthy"))
```

Summary statistics
```{r summary-stat,message=FALSE,warning=FALSE}
#   number of SIRS and negative controls in each block
table(sample_data(ps)$Sample_Type,sample_data(ps)$block)
```



Break phyloseq by blocks
```{r block-phylos,message=FALSE,warning=FALSE}
if(dim(otu_table(ps))[1]!=ntaxa(ps)){otu_table(ps) <- t(otu_table(ps))}

psBlockResult <- psBlockResults(ps, sampleTypeVar = "Sample_Type",sampleName = "SampleCode",blockVar = "block")
psByBlock <- psBlockResult[[1]]
psNCbyBlock <- psBlockResult[[2]]
psallzeroInNC <- psBlockResult[[3]]
psPlByBlock <- psBlockResult[[4]]

```

```{r estimate-neg-bio-para-ncontrols,message=FALSE,warning=FALSE}
alphaBetaNegControl <- alphaBetaNegControl(psNCbyBlock = psNCbyBlock)
```


```{r estimate-cont-for-plasma-sam,message=FALSE,warning=FALSE}
block <- 3
gammaPrior <- alphaBetaContInPlasma(psPlByBlock = psPlByBlock,psallzeroInNC = psallzeroInNC,blk = block,alphaBetaNegControl = alphaBetaNegControl)
```

For all samples in the block, for all taxa in the block, the estiamted real reads distribution
```{r estim-poster-real-reads,message=FALSE,warning=FALSE}
t1 <- proc.time()
posterior_intensity_all_taxa  <- samplingPosterior(psPlByBlock = psPlByBlock,blk = block,gammaPrior_Cont = gammaPrior, itera = 10000)
proc.time()-t1

knownContGamma_posteriorSignal <- list(gammaPrior,posterior_intensity_all_taxa)

saveRDS(knownContGamma_posteriorSignal,file = "./signalPosterior_gammaPrior.rds")
```


Save the results for each sample as a table in png format
```{r eval=FALSE}
knownContGamma_posteriorSignal <- readRDS(file=".signalPosterior_gammaPrior.rds")

gammPrior <- knownContGamma_posteriorSignal[[1]]

posterior_intensity_all_taxa <- knownContGamma_posteriorSignal[[2]]

blk <- 3

for(sam in 1:nsamples(psPlByBlock[[blk]])){
        
        posterior_taxa <- posterior_intensity_all_taxa[[sam]]
        acceptance_prob <- list()
        expected_posterior_real <- list()
        lower_limit_real <- list()
        upper_limit_real <- list()
        standDev_posterior_real <- list()
        upper_limit_cont <- list()
        lower_limit_cont <- list()
        naive_expected_real <- list()
        prevalence_zero_in_negative_control <- list()
        signal_to_noise_ratio_upper <- list()
        signal_to_noise_ratio_lower <- list()
        SNR <- list()
                for(taxa in 1:length(posterior_taxa)){
                        burnIn  <- 5000
                        acceptance_prob[[taxa]]  <-  1-mean(duplicated(posterior_taxa[[taxa]][-(1:burnIn),]))
                
                        expected_posterior_real[[taxa]] <- mean(posterior_taxa[[taxa]][-(1:burnIn),])
                          
                        hdi.v <- hdi(posterior_taxa[[taxa]][-(1:burnIn),],credMass = .95)
                        lower_limit_real[[taxa]] <- round(hdi.v[1],digits = 0)
                        upper_limit_real[[taxa]] <- round(hdi.v[2],digits = 0)
                        
                        b.int <- rgamma(5001,shape=gammPrior[[sam]][[1]][taxa],rate = gammPrior[[sam]][[2]][taxa])
                        
                        hdi.b <- hdi(b.int,credMass = .95)
                        lower_limit_cont[[taxa]] <- round(hdi.b[1],digits = 0)
                        upper_limit_cont[[taxa]] <- round(hdi.b[2],digits = 0)
                        
                        standDev_posterior_real[[taxa]] <- sd(posterior_taxa[[taxa]][-(1:burnIn),])
                        
                       naive_expected_real[[taxa]] <- gammPrior[[sam]][[3]][taxa]-(gammPrior[[sam]][[1]][taxa]/gammPrior[[sam]][[2]][taxa])
                        
                        prevalence_zero_in_negative_control[[taxa]] <-  gammPrior[[sam]][[5]][taxa]
                        
                        sig.noise.ratio <- posterior_taxa[[taxa]][-(1:burnIn),]/b.int
                        
                        sig.noise.ra_hdi <- hdi(sig.noise.ratio,credMass = .95)
                        signal_to_noise_ratio_upper[[taxa]] <- sig.noise.ra_hdi[[2]]
                        SNR[[taxa]] <- mean(posterior_taxa[[taxa]][-(1:burnIn),])/mean(b.int)
                        
                        signal_to_noise_ratio_lower[[taxa]] <- sig.noise.ra_hdi[[1]]
                }
        

                df <- data.frame(Species=taxa_names(psPlByBlock[[blk]]),xj=as.numeric(gammPrior[[sam]][[3]]),l.s=unlist(lower_limit_real),u.s=unlist(upper_limit_real),l.b=unlist(lower_limit_cont),u.b=unlist(upper_limit_cont),pre_zero_in_neg_cont=unlist(prevalence_zero_in_negative_control),sigToNoise_l=unlist(signal_to_noise_ratio_lower),sigToNoise_u=unlist(signal_to_noise_ratio_upper))

               
               df <- dplyr::arrange(filter(df,((l.s > u.b)&(l.s > 0))&(sigToNoise_l>1)),desc(xj))
               
                if(dim(df)[1]==0){
                        df <- data.frame(Species=NA)
                }
                
                filname <- paste("./",sample_names(psPlByBlock[[blk]])[sam],".png",sep="")
               png(filname, height = 600, width = 750)
                
                df.p <- tableGrob(df)
                
                libSize <- sum(as.numeric(gammPrior[[sam]][[3]]))
                
                title <- textGrob(paste(sample_names(psPlByBlock[[blk]])[sam],"lib=",libSize,sep=" "), gp = gpar(fontsize = 10))
                
                padding <- unit(0.5,"line")
                
                df.p <- gtable_add_rows(
                  df.p, heights = grobHeight(title) + padding, pos = 0
                )
                
                df.p <- gtable_add_grob(
                  df.p, list(title),
                  t = 1, l = 1, r = ncol(df.p)
                )
                
                grid.newpage()
                grid.draw(df.p)
                dev.off()
}
```
